### ISSUE TITLE
"invalid memory address or nil pointer dereference" when opening 7z file

### ISSUE THREAD

**Issue by rgmz** [bodgit/sevenzip#113]
When attempting to open [this file](https://github.com/apache/commons-compress/blob/277d6a0c2820548fd97748ec6aff92ceceb1fd35/src/test/resources/COMPRESS-492.7z), a panic is encountered. (That repository has some great test cases in general.)

```sh
# Program based on  https://pkg.go.dev/github.com/bodgit/sevenzip?utm_source=godoc#example-OpenReader
$ go run main.go

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x59b4c8]

goroutine 1 [running]:
github.com/bodgit/sevenzip.readStreamsInfo({0x650d88, 0xc0001a41e0})
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.4.3/types.go:513 +0x1e8
github.com/bodgit/sevenzip.readHeader({0x650d88, 0xc0001a41e0})
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.4.3/types.go:800 +0x73
github.com/bodgit/sevenzip.(*Reader).init(0xc0001d02d8, {0x650700?, 0xc0001a20b8}, 0x27)
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.4.3/reader.go:379 +0x825
github.com/bodgit/sevenzip.OpenReaderWithPassword({0x5fe82e, 0x1d}, {0x0, 0x0})
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.4.3/reader.go:211 +0x36b
github.com/bodgit/sevenzip.OpenReader(...)
        /home/user/go/pkg/mod/github.com/bodgit/sevenzip@v1.4.3/reader.go:228
main.main()
        /tmp/sevenzip/main.go:14 +0x3f
exit status 2
```

The issue _appears_ to be with ` s.unpackInfo.folder` here. Based on [the commit associated with that archive](https://github.com/apache/commons-compress/commit/277d6a0c2820548fd97748ec6aff92ceceb1fd35), it's possible for an archive to contain streams but no subStreamsInfo.

https://github.com/bodgit/sevenzip/blob/8185d4f1b66caf53cb939a56f84163471a7db0d3/types.go#L513

**Comment by bodgit** [comment]
v1.4.4 has been released that "fixes" this, in that you will get an error rather than a segfault and panic
