### ISSUE TITLE
sevenzip: TODO complex coders

### ISSUE THREAD

**Issue by Puyodead1** [bodgit/sevenzip#14]
Hello, I'm trying to use this library to extract some binary dependencies but am getting this error `sevenzip: TODO complex coders`

Archive in question is FFMPEG for Windows: https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2022-03-17-git-242c07982a-essentials_build.7z

**Comment by Puyodead1** [comment]
Actually it looks like this might be related to #6

**Comment by bodgit** [comment]
Yeah, it's almost certainly BCJ2 if the archive contains binaries/libraries.
