### ISSUE TITLE
 warning: a function definition without a prototype is deprecated in all versions

### ISSUE THREAD

**Issue by spectertian** [bodgit/sevenzip#217]
解压的时候提示
/Users/tian/go/pkg/mod/github.com/gen2brain/go-unarr@v0.1.2/unarrc/external/zlib/adler32.c:180:15: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]

**Comment by spectertian** [comment]
解带密码的提示  Failed to open file in archive: lzma: unsupported chunk header byte

**Comment by bodgit** [comment]
This isn't my library, there's no C code involved.
