### ISSUE TITLE
 解带密码的提示 Failed to open file in archive: lzma: unsupported chunk header byte

### ISSUE THREAD

**Issue by spectertian** [bodgit/sevenzip#220]
解带密码的提示 Failed to open file in archive: lzma: unsupported chunk header byte

**Comment by bodgit** [comment]
I need some sort of test case or example archive either as an attachment or link that demonstrates this bug.

**Comment by badandboy** [comment]
+1， 如果密码不对，都不知道错误是啥，怎么提示用户
