### ISSUE TITLE
How to extract

### ISSUE THREAD

**Issue by Thijxx** [bodgit/sevenzip#236]
How does one actually extract a file? There does not seem to be any example or any documentation on doing what it is supposed to do. Or am I missing something here?

**Comment by bodgit** [comment]
You asked me the same question two years ago in #50.

The docs are at https://pkg.go.dev/github.com/bodgit/sevenzip and there are examples there and in the README in the root of this repository.

It works almost exactly the same as `archive/zip` so it doesn't deal with writing out the files for you, that's the job of your code.

**Comment by Thijxx** [comment]
Almost one year later and I'm here again, was about to ask (apparently for the third time) for an example and how this actually extracts a file but I will not bother this time :D See you in a year or so!
