### ISSUE TITLE
about 444G big 7z file, Hangs for 8 hours, don't know what happened

### ISSUE THREAD

**Issue by hktalent** [bodgit/sevenzip#53]
open from lan network 444G big 7z file
Hangs for 8 hours, don't know what happened
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/18223385/206037722-0f4a505b-65ed-44d3-8118-9e4ca4bcf9f1.png">

**Comment by bodgit** [comment]
Does the archive contain lots of files or is it a small number of very big files? Either way it shouldn't take 8 hours to just get the archive contents so there's definitely something up. The archive contents are at the end of the archive file, so the code just reads some data from the start of the file that tells it where to seek to at the end of the file, does the seek, and then reads in the contents, which may be compressed and/or encrypted.

Ordinarily I'd ask if you can make the archive available, but I suspect you don't want to upload 444 GB, and I don't want to download it either!

Therefore you'll have to do a bit of debugging yourself, unfortunately. I would start by simply scattering some `fmt.Println` statements in this function https://github.com/bodgit/sevenzip/blob/master/reader.go#L261 and see how far it gets before it hangs. Bonus points for printing out the various offsets as it goes just in case I've done an invalid cast to/from `int64` somewhere.

**Comment by bodgit** [comment]
I just noticed you said the file is on a LAN share. Depending on what the protocol is (SMB/CIFS or NFS?) when seeking to the end of the archive to read in the file contents, the seek syscall may be implemented in a way that means it has to read the whole file from the network. So if you can, I'd copy the file locally and then see if you can still reproduce the problem.

**Comment by hktalent** [comment]
@bodgit thanks
There are more than 100 million small files, let me debug and see

**Comment by bodgit** [comment]
Ok, wow. That's going to mean some very big Golang slices.

**Comment by hktalent** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/18223385/206684875-f99bcf3e-cc83-41a1-96ee-53c7bfb5b268.png">

h.filesInfo.file  15087956
<img width="429" alt="image" src="https://user-images.githubusercontent.com/18223385/206684990-6ef27ec6-55ee-4395-a966-1babd58e3e95.png">

**Comment by hktalent** [comment]
There are a lot of optimizations here
for _, f := range xxx

<img width="834" alt="image" src="https://user-images.githubusercontent.com/18223385/206688452-91409b96-488e-40e5-8726-bbc19f9ab9e7.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/18223385/206689162-ab403cba-70c8-427b-9b37-c849c487f904.png">

**Comment by hktalent** [comment]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/18223385/206689661-8da7e905-ab7c-486e-8cc0-7b92c71935ea.png">
Debug is too complicated, too many loops consume a lot of time. It is recommended to optimize and read a file information and send it to chan for processing before continuing. Otherwise, the loop is too slow, and only you can optimize and debug it yourself.

You can programmatically build a 7z file of 20 million 0-byte files for debugging

**Comment by bodgit** [comment]
If you have an archive containing 20 million files, you are still going to end up with slices containing that many entries, that's unavoidable. The metadata is packed in a specific order that has to be read in sequence so this makes handing things off to channels tricky.

Consider this code which I think you've highlighted:
```golang
	for _, f := range u.folder { // 15,000,000+
		total := uint64(0)
		for _, c := range f.coder {
			total += c.out
		}

		f.size = make([]uint64, total)
		for i := range f.size {
			if f.size[i], err = readUint64(r); err != nil {
                                         // ^^^^^^^^^^^^^ has to be in sequence
				return nil, err
			}
		}
	}
```
That `readUint64()` has to be in the same order as the folders are packed. How would a channel help here?

Bear in mind that if the archive metadata is not compressed or encrypted, any offset within `r` has a 1:1 mapping with the underlying archive file on the disk, but if there's any compression or encryption involved that's no longer true. In order for a separate goroutine to read data, they would likely have to create their own copy of the stream and seek to the desired position by reading and discarding data, so you would potentially end up with lots more file I/O than just processing it sequentially.

**Comment by hktalent** [comment]
Well, it seems that I can only give up, decompress it externally and then process it
Originally intended to be done in memory to save disk space

**Comment by bodgit** [comment]
I will try and create a test archive containing lots of files and see where the bottleneck is. I don't expect the code to be fast, but I'd expect it to complete faster than 8 hours. Like I said, eliminating the LAN and also ensuring your machine isn't starved of memory would be my first step.

How quickly does `7z l -slt archive.7z` take to run on the same archive?

**Comment by hktalent** [comment]
![image](https://user-images.githubusercontent.com/18223385/206704121-0a880336-15d8-4758-8dfd-1725bde0fc3b.jpeg)
I'm using the command to decompress and process, I don't know how long it will take
You can programmatically build such a sample file

**Comment by hktalent** [comment]
I don’t know this, I currently use 7z x -aou xxx.7z to decompress, but I found that the decompressed directory
if err := filepath.WalkDir("xxx/", Visit); nil != err {
//if err := filepath.WalkDir("/volume1/home/admin/MyWork/sgk/BreachCompilation/data", Visit); nil != err {
fmt.Printf("filepath.WalkDir() returned %v\n", err)
}
still very slow
