### ISSUE TITLE
seek over file in archive

### ISSUE THREAD

**Issue by mac2000** [bodgit/sevenzip#59]
I'm not sure if that's possible, but it will be really nice to have `ReadSeekCloser` instead of `ReadCloser` which should allow us to read desired bytes from files inside the archive.

**Comment by mac2000** [comment]
From my understanding, it is not possible, e.g., we can not seek because we do now know offset upfront decompressing, also from what I see, built-in go zip also uses `ReadCloser`.

PS: yes, theoretically we can work with offsets of compressed file but still it seems like even native 7z libs does not have this which makes me believe it wont be doable

**Comment by bodgit** [comment]
You're right, it's not really possible.

You can _sort of_ implement seeking, but only to the same offset or further forward in the file by just reading and discarding bytes, so it's not any more efficient as you still do the same amount of I/O, there's no way to just jump to a particular offset.
