### ISSUE TITLE
Support BCJ method

### ISSUE THREAD

**Issue by bodgit** [bodgit/sevenzip#62]
Decompression method: `3.3.1.3`

The GameCube homebrew "Swiss" is distributed in a 7z that uses BCJ for some of the binaries.

**Comment by rusq** [comment]
Upvote this, [MAME archive](https://github.com/mamedev/mame/releases/download/mame0253/mame0253b_64bit.exe) uses BCJ as well.

**Comment by bodgit** [comment]
> I think I found the original [C implementation](https://github.com/mcmilk/7-Zip/blob/e87b0c0e43231bef1007d421296aa54eaf8d70b0/C/Bra86.c#L10) in the 7z source code, but I'm sure you've seen it already.

I think there's some additional scaffolding around that code but yes, that's essentially the implementation. It should be easier than BCJ2, I just need to find some time to do it.

**Comment by bodgit** [comment]
I've just created #85 which adds support for self-extracting archives. It scans the first 1 MiB of the file which should be enough to find the signature without scanning the whole file.

Annoyingly on some platforms, the signature can appear more than once (usually twice) and the first occurrence is in the executable that is at the beginning of the file so there's some heuristics to work out which offset is the correct one.

I've tested it on that MAME archive and it works correctly.

**Comment by rusq** [comment]
That's perfect @bodgit , thank you! I'll aim to try it out on the weekend.

I'm really amazed how you put so much effort to implement the 7z in go, tbh, kudos!

**Comment by rusq** [comment]
Hey @bodgit, I have tried it with mame, it works (for both: SFX scan and BCJ compressed files).  Thanks again!

**Comment by bodgit** [comment]
Thanks for testing and confirming!
