### ISSUE TITLE
sevenzip as a guide

### ISSUE THREAD

**Issue by zfLQ2qx2** [bodgit/sevenzip#79]
@bodgit This isn't about sevenzip directly but could really use your insight if you have a moment.

Just for kicks I thought I would try to manually decode a 7zip archive just so I can understand the format better. I've been using the sevenzip code as a guide.

       Signature: 377abcaf271c
         Version: 0004
  StartHeaderCRC: 886524f2
NextHeaderOffset: 0000000000ad6d77 (11365751)
  NextHeaderSize: 0000000000000025 (37)
   NextHeaderCRC: 0fc78a39
XXX kEncodedHeader 0x17
&main.streamsInfo{packInfo:(*main.packInfo)(0x140000a8180), unpackInfo:(*main.unpackInfo)(0x140000c0000), subStreamsInfo:(*main.subStreamsInfo)(nil)}
&main.packInfo{position:0xad6cd6, streams:0x1, size:[]uint64{0xa1}, digest:[]uint32(nil), defined:[]bool(nil)}
&main.unpackInfo{folder:[]*main.folder{(*main.folder)(0x140000c2000)}, digest:[]uint32{0x62bad49f}, defined:[]bool{true}}
&main.folder{in:0x1, out:0x1, packedStreams:0x1, coder:[]*main.coder{(*main.coder)(0x140000aa040)}, bindPair:[]*main.bindPair{}, size:[]uint64{0x14e}, packed:[]uint64{0x0}}
&main.coder{id:[]uint8{0x3, 0x1, 0x1}, in:0x1, out:0x1, properties:[]uint8{0x5d, 0x0, 0x10, 0x0, 0x0}}

I'm trying to decompress the lzma encoded headers. I've believe I've located the position of the compressed headers relative to the signature header at 11365590+32. The compressed headers look like 161 bytes, and uncompressed size looks like 334. I can see that they are compressed with lzma (0x3, 0x1, 0x1). 

I should just be able to seek to 11365590+32, copy 161 bytes to a []byte, create call bytes.NewReader on the []byte, and pass the bytes.Reader to lzma.NewReader(). However lzma.NewReader gives me this error: newRangeDecoder: first byte not zero

If I dump the 161 bytes to disk I can see the first two bytes are 0x00 so I think the error message from the lzma module (github.com/ulikunitz/xz/lzma) might be misleading.

00000000: 0000 8133 07ae 0fd9

So seems I'm missing something someplace. I'm hoping you might see what it is since you've done this before.

**Comment by bodgit** [comment]
If it's LZMA, then the stream seems to need to have the size prepended to it, see the code here:

https://github.com/bodgit/sevenzip/blob/15d9bcebce25e3138dc5b6e90a401890a46f4d6f/internal/lzma/reader.go#L41-L44

Every decoder gets passed the stream size and optionally some property bytes which it's free to interpret and use how it sees fit. So in this case I just write the size to a buffer (in little endian byte order) and then use an `io.MultiReader` to concatenate that and the actual stream together.

So what is probably happening is your LZMA reader is reading the first 8 bytes as the size and *then* complaining the first byte after that isn't zero.

Hope that helps.

**Comment by zfLQ2qx2** [comment]
@bodgit That was it! The properties bytes from the folder coder + the size of the uncompressed data as a little endian uint64 + the uncompressed data was the correct input. How did you ever figure that one out? I can't find it discussed anywhere. Thank you very much for sharing your expertise with me!
