### ISSUE TITLE
Empty File processing issue

### ISSUE THREAD

**Issue by hongtw** [bodgit/sevenzip#87]
for `7-zip archive data, version 0.4`, below code would work

types.go  697 ~710

```golang		
		case idEmptyFile:
			empty, err := readBool(r, emptyStreams)
			if err != nil {
				return nil, err
			}

			j := 0

			for i := range f.file {
				if f.file[i].isEmptyStream {
					f.file[i].isEmptyFile = empty[j]
				}
				j++
			}
```
			
But for `7-zip archive data, version 0.3`, `empty slice` may be  `index out of range`.
I found that in `version 0.3`, the empty file does not appear only in front of the `f.file`,  which causes the index of `empty` to be taken later on to exceed.

Should `j++` write in `isEmptyStream` condition , like below ?

```golang
		case idEmptyFile:
			empty, err := readBool(r, emptyStreams)
			if err != nil {
				return nil, err
			}

			j := 0

			for i := range f.file {
				if f.file[i].isEmptyStream {
					f.file[i].isEmptyFile = empty[j]
					j++
				}
			}
```

**Comment by bodgit** [comment]
Can you attach some (ideally small) example archives with empty files that demonstrate it working and not working for the two different archive versions?

I like to add test cases for issues like this to make sure I don't accidentally revert fixes later on.

**Comment by hongtw** [comment]
Here is sample, there are two different versions of .7z in it  (`withEmptyFileVersion3.7z` and `withEmptyFileVersion4.7z`):
[sample.zip](https://github.com/bodgit/sevenzip/files/11560957/sample.zip)

Both `.7z` files contain the same content, both are 2 empty `.txt` and 1 `.txt` with text

for file `withEmptyFileVersion3.7z` with `version 0.3`
```
$ file withEmptyFileVersion3.7z
withEmptyFileVersion3.7z: 7-zip archive data, version 0.3

$ 7z l  withEmptyFileVersion3.7z

7-Zip [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.05 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)

Scanning the drive for archives:
1 file, 195 bytes (1 KiB)

Listing archive: withEmptyFileVersion3.7z

--
Path = withEmptyFileVersion3.7z
Type = 7z
Physical Size = 195
Headers Size = 186
Method = LZMA:16
Solid = -
Blocks = 1

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2023-05-25 11:24:23 ....A            4            9  something.txt
2023-05-25 11:24:22 ....A            0            0  empty.1.txt
2023-05-25 11:24:21 ....A            0            0  empty.2.txt
------------------- ----- ------------ ------------  ------------------------
2023-05-25 11:24:23                  4            9  3 files
```

for file `withEmptyFileVersion3.7z` with `version 0.4`
```
$ file withEmptyFileVersion4.7z
withEmptyFileVersion4.7z: 7-zip archive data, version 0.4

$ 7z l  withEmptyFileVersion4.7z

7-Zip [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.05 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)

Scanning the drive for archives:
1 file, 192 bytes (1 KiB)

Listing archive: withEmptyFileVersion4.7z

--
Path = withEmptyFileVersion4.7z
Type = 7z
Physical Size = 192
Headers Size = 184
Method = LZMA2:12
Solid = -
Blocks = 1

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2023-05-24 11:21:02 ....A            0            0  empty.1.txt
2023-05-24 11:21:04 ....A            0            0  empty.2.txt
2023-05-24 11:21:16 ....A            4            8  something.txt
------------------- ----- ------------ ------------  ------------------------
2023-05-24 11:21:16                  4            8  3 files
```

And  `withEmptyFileVersion3.7z` would got `panic: runtime error: index out of range [2] with length 2`

**Comment by bodgit** [comment]
The only difference between the two archives seems to be the order of the files within the archive. When the empty files are at the beginning there's no panic but when the empty files appear later, there's a panic.

It looks like your suggestion is correct, the `j++` just needs to be moved up within the conditional block.

**Comment by bodgit** [comment]
I've made a v1.4.2 release with this issue (hopefully) fixed. Thanks for the bug report!

**Comment by ADRIEN9631** [comment]
> I've made a v1.4.2 release with this issue (hopefully) fixed. Thanks for the bug report!

Hi, I've encountered the same problem in tag v1.3.0, so I found this issue and review the fix. I'm confusing why case 'idEmptyStream' and 'idEmptyFile' read different count of bool values, I think the bitset after property 'IdEmptyFile' represents empty file flags of all the files in 7z, not only files with empty stream flag.
```
		switch property {
		case idEmptyStream:
			empty, err := readBool(r, files)
			if err != nil {
				return nil, err
			}

			for i := range f.file {
				f.file[i].isEmptyStream = empty[i]

				if empty[i] {
					emptyStreams++
				}
			}
		case idEmptyFile:
			empty, err := readBool(r, emptyStreams)
			if err != nil {
				return nil, err
			}

			j := 0

			for i := range f.file {
				if f.file[i].isEmptyStream {
					f.file[i].isEmptyFile = empty[j]
				}
				j++
			}
```
